version: "3.9"
services:
  omp-php:
    build:
      ./docker/php
    hostname: "omp-php"
    container_name: "omp-php"
    working_dir: /www/vhosts/omp
    links:
      - omp-db
    #user: www-data:www-data
    volumes:
    - ./omp:/www/vhosts/omp:cached
    entrypoint: ["php-fpm"]
  omp-nginx:
    build:
      ./docker/nginx
    hostname: "omp-nginx"
    container_name: "omp-nginx"
    working_dir: /www/vhosts/omp
    links:
      - omp-php
    #user: nginx:nginx
    ports:
    - 80:80
    volumes:
      - ./omp:/www/vhosts/omp:cached
    entrypoint: ["nginx", "-g", "daemon off;"]
  omp-db:
    image: mysql:5.7
    platform: linux/x86_64
    hostname: "omp-db"
    container_name: "omp-db"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:delegated
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vagrant
      MYSQL_DATABASE: omp
      MYSQL_USER: vagrant
      MYSQL_PASSWORD: vagrant
  omp-node6:
    build:
      ./docker/node
    platform: linux/x86_64
    hostname: "omp-node6"
    container_name: "omp-node6"
    working_dir: /www/vhosts/omp
    volumes:
      - ./omp:/www/vhosts/omp:cached
